version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run lint
            - run: npm test
workflows:
    main:
      jobs:
        - test