version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: sudo apt-get update -y
      - run:
          command: sudo apt-get install -y xvfb
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm start

      - store_artifacts:
          path: ./cypress/screenshots/
      - store_artifacts:
          path: ./cypress/videos/
workflows:
    main:
      jobs:
        - test